name: login_with_connect
description: Flutter package to sign in with Connect Persona (app first, web fallback).
version: 0.2.2
homepage:

environment:
  sdk: ">=3.10.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  app_links: ^6.3.2
  flutter_web_auth_2: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
