name: login_with_connect
description: Flutter package to sign in with Connect Persona (app first, web fallback).
version: 0.3.2
homepage: https://github.com/ankaEK/connect-login-sdk
repository: https://github.com/ankaEK/connect-login-sdk

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  app_links: ^6.3.2
  flutter_web_auth_2: ^5.0.1
  app_links_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
